index:
    path: /
    controller: App\Controller\Controller::index

doctor_add:
    path: /doctor
    methods: POST
    controller: App\Action\AddDoctor

doctor_get:
    path: /doctor
    methods: GET
    controller: App\Controller\Controller::getDoctorAction

slots_get:
    path: /slots/{doctorId}
    methods: GET
    controller: App\Controller\Controller::getSlotsAction

slots_add:
    path: /slots/{doctorId}
    methods: POST
    controller: App\Controller\Controller::addSlotsAction
