index:
    path: /
    controller: App\Controller\Controller::index

doctor:
    path: /doctor
    controller: App\Controller\Controller::doctor

slots_get:
    path: /slots/{doctorId}
    methods: GET
    controller: App\Controller\Controller::showSlots

slots_save:
    path: /slots/{doctorId}
    methods: POST
    controller: App\Controller\Controller::saveSlots
